blank_issues_enabled: false
contact_links:
  - name: 📖 View Documentation
    url: https://xindi-technology.github.io/rspress-theme-aim/
    about: Check the documentation before opening an issue
  - name: ❓ Ask a Question
    url: https://github.com/XinDi-Technology/rspress-theme-aim/discussions/new?category=q-a
    about: Ask questions about the project
  - name: 💬 General Discussions
    url: https://github.com/XinDi-Technology/rspress-theme-aim/discussions
    about: Join the community discussions
